### ISSUE TITLE
README.rst is not packaged on pypi

### ISSUE THREAD

**Issue by stephan-hof** [wichert/collective.recipe.modwsgi#5]
Hello,
I tried to use the 1.5 from pypi however the setup.py cannot be executed.
error: README.rst: No such file or directory

I tried the command to generate a sdist myself and this error occurs.
warning: sdist: standard file not found: should have one of README, README.txt

So it seems like GitHub renders the README now, but distutils does not package them :(

**Comment by wichert** [comment]
Damn - I hate it when that happens. Can you check if 1.6 works?

**Comment by stephan-hof** [comment]
Im not an expert in this packaging stuff. What about adding this line to the Manifest.in file

include README.rst

**Comment by stephan-hof** [comment]
1.6 works great, thanks.
